const audios = require("./audios.json")
const buttons = require("./buttons.json")
const cards = require("./cards.json")
const contactForm = require("./contactForm.json")
const icons = require("./icons.json")
const images = require("./images.json")
const impressum = require("./impressum.json")
const hero = require("./hero.json")
const links = require("./links.json")
const list = require("./list.json")
const menu = require("./menu.json")
const pickers = require("./pickers.json")
const products = require("./products.json")
const team = require("./team.json")
const testData = require("./testData.json")
const videos = require("./videos.json")

export {audios, contactForm, images, hero, impressum, list, menu, products, team, testData, buttons, pickers, videos, cards, links, icons}